---
bin_dir: "/opt/bin"
argo_jwt_token: "{{ argo_jwt_token_prod if k8s_cluster_environment == 'prod' else argo_jwt_token_stage }}"

argo_jwt_token_prod: !vault |
# You would use ansible-vault to encrypt your jwt token and stash it here
